README.md

As the project stands today, we cannot build a QEMU reference integration but only the boards listed below.

docs: Remove mention to QEMU

---

src/main.c

We get linking errors because `CONFIG_MENDER_LOG_LEVEL` is only defined in the `mender-mcu` module. In addition, it might be better to keep the log-levels contained within a module.
This reverts commit 6e00f35c4c331e5396587030f3188fe768e92fa3.
Ticket: None
Changelog: Title

fix: Revert "chore: Use the same log level as mender-mcu"

---

src/main.c

Inventory is no longer an addon, but an optional built-in feature.
Ticket: None
Changelog: Title

fix: change to correct inventory config option

---

src/utils/netup.c

Removes 'implicit declaration of snprintf' warnings
Ticket: None

chore: include <stdio.h> to remove compilation warnings

---

.gitlab-ci.yml
Dockerfile.ci

Added a job that creates a docker image with a workspace containing the zephyr sdk with as few toolchains as possible and a cached version of mender-mcu-integration.
Added a job that utilizes this image and the cached workspace to build all the supported boards. You can also specify the revision of mender-mcu by manually changing `MENDER_MCU_REVISION`.
Ticket: MEN-7597

ci: jobs to build workspace and board

---

CMakeLists.txt
config-tls-mender.h
prj.conf

By reducing the size of the TLS output buffer we can also reduce the size of the MbedTLS' heap buffer (where MbedTLS allocates its internal buffers from).
Ticket: MEN-7807

fix: Reduce the size of the MbedTLS' heap buffer

---

.gitlab-ci.yml
Dockerfile.ci
boards/esp32_ethernet_kit_procpu.conf
prj.conf
src/main.c
west.yml

The updated config options are really just based on trial and error on arm. The net socket timeout can probably be set a bit higher, same with the max open file descriptors; what do you think a reasonable value is?

Update Zephyr to v4.0.0 and use main mender-mcu

---

west.yml

Allowlist allows us to only import the modules we need for our project. By default, every module from Zephyr is included.

chore: filter imported modules with allowlist

---

README.md

Required for a succesful build for all of the ESP32 boards we mention.
Ticket: none

fix: Add a note about the blobs needed for ESP32

---

.gitlab-ci.yml

Makes it possible to checkout to branches like `pull/123/head`

ci: allow `MENDER_MCU_REVISION` to fetch PR branches

---

.gitmodules
CMakeLists.txt
tests/integration/README.md
tests/integration/conftest.py
tests/integration/definitions.py
tests/integration/device.py
tests/integration/helpers.py
tests/integration/server.py
tests/integration/src/main.c
tests/integration/src/modules/test-update-module.c
tests/integration/src/modules/test-update-module.h
tests/integration/test_mender_mcu.py

This does not run in any pipeline, nor does it use any docker-images as of now
To run the sample test, navigate to the integration directory and run e.g. `pytest -s`. You must set the following variables in manually inside the test:
* `tentant_token`
* `auth_token`
* `device_id`
The test is configured to run using hosted.mender.io, as I couldn't get the demo servers to work (possibly due to the self-signed certificate)
Note that this test also uses the `native_sim` board, so it will also require you to setup the network - and the current README doesn't entirely cover it.

[draft] test: integration test framework

---

.gitlab-ci.yml

There is no need to rebuild the workspace each time we trigger this pipeline from mender-mcu.

ci: don't rebuild workspace unnecessarily on triggers

---

.gitlab-ci.yml
tests/integration/conftest.py
tests/integration/device.py
tests/integration/test_mender_mcu.py

I haven't been able test the coverage job in ci yet - but it's essentially a copy of the job in mender-mcu with the variables swapped out. 
The build-dir situation got a bit messy - so I landed on a fixture, which adds an extra argument to the device constructor, but I guess it's fine, unless anyone else has a better idea.

test: add coverage

---

src/modules/noop-update-module.c

fix: Use `mender_calloc()` when allocating the noop UM

---

src/main.c
src/utils/callbacks.h
tests/integration/src/modules/test-update-module.c
tests/integration/src/modules/test-update-module.h

Rebase on top of main.
Only the last two commits are new:
* update the inclusions of header files after the reorganization
* use `mender_calloc` instead of  `calloc` in the test-update-module
We also need https://github.com/mendersoftware/mender-mcu/pull/155 for it to compile because of the weak functions

Rebase feature integration tests branch

---

.gitlab-ci.yml

We don't have any coverage to publish, as there are no tests running yet

ci: disable `publish:tests` job

---

src/main.c

Instead of foo-bar, let's report that the devices run the `mender-mcu-integration` app.
Ticket: none

chore: Make the sample inventory nicer

---

prj.conf
src/main.c
src/utils/callbacks.h

This was changed to adapt to changes in the mender-mcu client, but was later reverted due to bad conflict resolution in 5065a57ccc26e04577b7bebdfdb9525bb3aa724b.
Ticket: MEN-7676

fix: `deployment_status_cb` should take a `const char *desc`

---

tests/integration/src/callbacks.c

Follow-up from https://github.com/mendersoftware/mender-mcu-integration/pull/63

chore: use const in test `mender_deployment_status_cb`

---

prj.conf

It is the default value, but by setting it in the application prj.conf we make it more intuitive for users to modify as desired after experimenting with interactive (but temporary) Kconfig settings.

MEN-8254: Explicitly select hosted Mender USA

---

.gitlab-ci.yml

Modified the rule in `publish:tests` to make sure it only runs on
protected branches, as that is when `test:integration` runs. Without
this, a trigger pipeline with an unprotected mender-mcu-integration
pipeline branch will run the `publish:tests` job without
`test:integration`

ci: add rule to publish:tests

---

CMakeLists.txt

Otherwise with no Mender MCU enabled (not onprem but also not any of the hosted Mender flavors) the cmake configure step fails.

build: Modify if statement for opt-in

---

tests/integration/integration_tests.conf
tests/integration/tests/test_mender_mcu.py
tests/integration/tests/test_state_machine.py

So that it is not in the way if/when we decide to modify the default `MENDER_DEVICE_TYPE`.

MEN-8292: Use an specific Device Type for integration tests

---

src/main.c

In practice is the same, but it makes of a better demo use case to actually set it to something than relying on the module's default.

MEN-8292: Set device type and don't rely on the default

---

CMakeLists.txt

Get the certificates from docs.mender.io rather than directly from the providers.
Ticket: MEN-8204

chore: get certificates from mender-docs

---

Dockerfile.ci

Old debian packages repository has been migrated
into two separated package repositories:
* workstation-tool
* device-components
From now on packages should be installed from the
new repositories.
Ticket: QA-1090
Changelog: Use the new package repositories

chore: Use the new package repositories

---

prj.conf
src/utils/netup.c
sysbuild-mcuboot.conf
west.yml

* replace deprecated `SB_CONFIG_MCUBOOT_MODE_SWAP_WITHOUT_SCRATCH` with `SB_CONFIG_MCUBOOT_MODE_SWAP_USING_MOVE`
From
https://docs.zephyrproject.org/latest/releases/migration-guide-4.1.html:
```
The Kconfig ``SB_CONFIG_MCUBOOT_MODE_SWAP_WITHOUT_SCRATCH`` has been deprecated and replaced
with ``SB_CONFIG_MCUBOOT_MODE_SWAP_USING_MOVE``, applications should be updated to select this
new symbol if they were selecting the old symbol.
```
* set `mgmt_event` type to `uint64_t`
From https://docs.zephyrproject.org/latest/releases/migration-guide-4.2.html:
The management event type is changed from `uint32_t` to `uint64_t`
* explicitly enable `POSIX_C_LANG_SUPPORT_R`
The General ISO C Library is needed to get the ISO 8601 timestamps we
need for the deployment logs.
* use cmsis-6 …

feat: migrate to Zephyr 4.2.0
